stages:
  extract_sample:
    cmd: python src/extract_sample.py --input_path data/raw/lewtun-drug-reviews/train.jsonl
      --output_path data/raw/lewtun-drug-reviews/sample_train.jsonl
    deps:
    - data/raw/lewtun-drug-reviews/train.jsonl
    - src/extract_sample.py
    params:
    - RANDOM_SEED
    - extract_sample
    outs:
    - data/raw/lewtun-drug-reviews/sample_train.jsonl:
        cache: false
        persist: true
  preprocess_train:
    cmd: python src/preprocessing.py --input_path data/raw/lewtun-drug-reviews/${train_data_path}.jsonl
      --output_path data/preprocessed/procd_${train_data_path}.csv
    deps:
    - data/raw/lewtun-drug-reviews/${train_data_path}.jsonl
    - src/preprocessing.py
    params:
    - train_data_path
    outs:
    - data/preprocessed/procd_${train_data_path}.csv:
        cache: true
        persist: true
  feature_engineering_train:
    cmd: python src/feature_engineering.py --procd_data_path data/preprocessed/procd_${train_data_path}.csv
    deps:
    - data/preprocessed/procd_${train_data_path}.csv
    - src/feature_engineering.py
    params:
    - RANDOM_SEED
    - train_data_path
    - procd_text
    - feature_engineering
    outs:
    - data/features/${procd_text}/dictionary_${feature_engineering.ngram}.pkl:
        cache: true
        persist: true
    - data/features/${procd_text}/bow_${feature_engineering.ngram}_corpus.pkl:
        cache: true
        persist: true
    - data/features/${procd_text}/tfidf_${feature_engineering.ngram}_corpus.pkl:
        cache: true
        persist: true
  #clustering_bert_train:
  #  cmd: python src/clustering.py --model_path data/features/${procd_text}/bert_embeddings.pkl
  #    --log_dir clustering_bert
  #  deps:
  #  - data/features/${procd_text}/bert_embeddings.pkl
  #  - src/clustering.py
  #  params:
  #  - RANDOM_SEED
  #  - procd_text
  #  - clustering_bert
    #outs:
    #- models/${procd_text}/bert_${clustering_bert.algorithm}.pkl:
    #    cache: false
    #    persist: true
  topic_modeling:
    cmd: python src/topic_modeling.py --procd_data_path data/preprocessed/procd_${train_data_path}.csv
      --dictionary_path data/features/${procd_text}/dictionary_${feature_engineering.ngram}.pkl
    deps:
    - data/preprocessed/procd_${train_data_path}.csv
    - data/features/${procd_text}/${topic_modeling.feature}_${feature_engineering.ngram}_corpus.pkl
    - data/features/${procd_text}/dictionary_${feature_engineering.ngram}.pkl
    #- models/${procd_text}/bert_${clustering_bert.algorithm}.pkl
    - src/topic_modeling.py
    params:
    - RANDOM_SEED
    - train_data_path
    - feature_engineering.ngram
    - procd_text
    - topic_modeling
  preprocess_test:
    cmd: python src/preprocessing.py --input_path data/raw/lewtun-drug-reviews/${test_data_path}.jsonl
      --output_path data/preprocessed/procd_${test_data_path}.csv
    deps:
    - data/raw/lewtun-drug-reviews/${test_data_path}.jsonl
    - src/preprocessing.py
    params:
    - test_data_path
    outs:
    - data/preprocessed/procd_${test_data_path}.csv:
        cache: true
        persist: true
  evaluate_topic_model:
    cmd: python src/evaluate_topic_model.py --topic_model_path 
      models/${procd_text}/${topic_modeling.algorithm}_${topic_modeling.feature}_${feature_engineering.ngram}_model.pkl
      --dictionary_path data/features/${procd_text}/dictionary_${feature_engineering.ngram}.pkl
    deps:
    - models/${procd_text}/${topic_modeling.algorithm}_${topic_modeling.feature}_${feature_engineering.ngram}_model.pkl
    - data/features/${procd_text}/dictionary_${feature_engineering.ngram}.pkl
    - src/evaluate_topic_model.py
    outs:
    - data/evaluate/topic_keywords.csv
    - data/evaluate/topics_dist_train.csv
    - data/evaluate/topics_dist_test.csv
metrics:
- cross_validation/metrics.json
- clustering_bert/metrics.json
- feature_engineering/metrics.json
- topic_modeling/metrics.json
- evaluate_topic_model/metrics.json
plots:
- cross_validation/plots/metrics:
    x: step
- clustering_bert/plots/metrics:
    x: step
- feature_engineering/plots/metrics:
    x: step
- topic_modeling/plots/metrics:
    x: step
- evaluate_topic_model/plots/metrics:
    x: step
params:
- cross_validation/params.yaml
