stages:
  extract_sample:
    cmd: python src/extract_sample.py --input_path data/raw/lewtun-drug-reviews/train.jsonl
      --output_path data/raw/lewtun-drug-reviews/sample_train.csv --fraction ${extract_sample.fraction}
      --stratify_column ${extract_sample.stratify_column}
    deps:
    - data/raw/lewtun-drug-reviews/train.jsonl
    - src/extract_sample.py
    params:
    - extract_sample.fraction
    - extract_sample.stratify_column
    outs:
    - data/raw/lewtun-drug-reviews/sample_train.csv
  preprocess:
    cmd: python src/preprocessing.py --input_path data/raw/lewtun-drug-reviews/sample_train.csv
      --output_path data/preprocessed/lewtun-drug-reviews/procd_sample_train.csv
    deps:
    - data/raw/lewtun-drug-reviews/sample_train.csv
    - src/preprocessing.py
    outs:
    - data/preprocessed/lewtun-drug-reviews/procd_sample_train.csv
