stages:
  extract_sample:
    cmd: python src/extract_sample.py --input_path data/raw/lewtun-drug-reviews/train.jsonl
      --output_path data/raw/lewtun-drug-reviews/sample_train.csv
    deps:
    - data/raw/lewtun-drug-reviews/train.jsonl
    - src/extract_sample.py
    params:
    - RANDOM_SEED
    - extract_sample
    outs:
    - data/raw/lewtun-drug-reviews/sample_train.csv
  preprocess_train:
    cmd: python src/preprocessing.py --input_path ${train_data_path} --output_path
      data/preprocessed/procd_train.csv
    deps:
    - ${train_data_path}
    - src/preprocessing.py
    params:
    - train_data_path
    outs:
    - data/preprocessed/procd_train.csv
  feature_engineering_train:
    cmd: python src/feature_engineering.py --input_path data/preprocessed/procd_train.csv
    deps:
    - data/preprocessed/procd_train.csv
    - src/feature_engineering.py
    params:
    - RANDOM_SEED
    - feature_engineering
    outs:
    - data/features/dictionary.pkl
    - data/features/bow_corpus.pkl
    - data/features/tfidf_corpus.pkl
    - data/features/bert_embeddings.pkl
  clustering_bert_train:
    cmd: python src/clustering.py --model_path data/features/bert_embeddings.pkl --log_dir
      clustering_bert
    deps:
    - data/features/bert_embeddings.pkl
    - src/clustering.py
    params:
    - RANDOM_SEED
    - clustering_bert
    outs:
    - models/bert_kmeans.pkl
    - models/bert_dbscan.pkl
    - models/bert_hierarchical.pkl
  #topic_modeling_bow_tfidf_sample_train:
  #  cmd: python src/topic_modeling.py --procd_data_path data/preprocessed/lewtun-drug-reviews/procd_sample_train.csv
  #    --bow_corpus_path data/features/bow_corpus.pkl --tfidf_corpus_path data/features/tfidf_corpus.pkl
  #    --dictionary_path data/features/dictionary.pkl --lda_bow_model_path models/lda_bow_model.pkl
  #    --nmf_bow_model_path models/nmf_bow_model.pkl --lda_tfidf_model_path models/lda_tfidf_model.pkl
  #    --nmf_tfidf_model_path models/nmf_tfidf_model.pkl --lda_bow_vis_path plots/lda_bow_vis.html
  #    --lda_tfidf_vis_path plots/lda_tfidf_vis.html --nmf_bow_vis_path plots/nmf_bow_vis.html
  #    --nmf_tfidf_vis_path plots/nmf_tfidf_vis.html
  #  deps:
  #  - data/preprocessed/lewtun-drug-reviews/procd_sample_train.csv
  #  - data/features/dictionary.pkl
  #  - data/features/bow_corpus.pkl
  #  - data/features/tfidf_corpus.pkl
  #  - data/features/word2vec_model.pkl
  #  - data/features/bert_embeddings.pkl
  #  - src/topic_modeling.py
  #  params:
  #  - RANDOM_SEED
  #  - topic_modeling
  #  outs:
  #  - models/lda_bow_model.pkl
  #  - models/nmf_bow_model.pkl
  #  - models/lda_tfidf_model.pkl
  #  - models/nmf_tfidf_model.pkl
  #  - plots/lda_bow_vis.html
  #  - plots/lda_tfidf_vis.html
  #  - plots/nmf_bow_vis.html
  #  - plots/nmf_tfidf_vis.html
  #clustering_bow_tfidf_sample_train:
  #  cmd: python src/clustering.py --model_paths 
  #    "models/lda_bow_model.pkl,models/lda_tfidf_model.pkl,models/nmf_bow_model.pkl,models/nmf_tfidf_model.pkl"
  #    --corpus_paths "data/features/bow_corpus.pkl,data/features/tfidf_corpus.pkl"
  #    --log_dir clustering_bow_tfidf
  #  deps:
  #  - models/lda_bow_model.pkl
  #  - models/lda_tfidf_model.pkl
  #  - models/nmf_bow_model.pkl
  #  - models/nmf_tfidf_model.pkl
  #  - data/features/bow_corpus.pkl
  #  - data/features/tfidf_corpus.pkl
  #  - src/clustering.py
  #  params:
  #  - RANDOM_SEED
  #  - clustering
  #  outs:
  #  - models/lda_bow_kmeans.pkl
  #  - models/lda_bow_dbscan.pkl
  #  - models/lda_bow_hierarchical.pkl
  #  - models/lda_tfidf_kmeans.pkl
  #  - models/lda_tfidf_dbscan.pkl
  #  - models/lda_tfidf_hierarchical.pkl
  #  - models/nmf_bow_kmeans.pkl
  #  - models/nmf_bow_dbscan.pkl
  #  - models/nmf_bow_hierarchical.pkl
  #  - models/nmf_tfidf_kmeans.pkl
  #  - models/nmf_tfidf_dbscan.pkl
  #  - models/nmf_tfidf_hierarchical.pkl
metrics:
- feature_engineering/metrics.json
- clustering_bert/metrics.json
plots:
- feature_engineering/plots/metrics:
    x: step
- clustering_bert/plots/metrics:
    x: step
