stages:
  extract_sample:
    cmd: python src/extract_sample.py --input_path data/raw/lewtun-drug-reviews/train.jsonl
      --output_path data/raw/sample_train.csv --fraction
      ${extract_sample.fraction} --stratify_column ${extract_sample.stratify_column}
    deps:
    - data/raw/lewtun-drug-reviews/train.jsonl
    - src/extract_sample.py
    outs:
    - data/raw/sample_train.csv
