stages:
  extract_sample:
    cmd: python src/extract_sample.py --input_path data/raw/lewtun-drug-reviews/train.jsonl
      --output_path data/raw/lewtun-drug-reviews/sample_train.jsonl
    deps:
    - data/raw/lewtun-drug-reviews/train.jsonl
    - src/extract_sample.py
    params:
    - RANDOM_SEED
    - extract_sample
    outs:
    - data/raw/lewtun-drug-reviews/sample_train.jsonl
  preprocess_train:
    cmd: python src/preprocessing.py --input_path data/raw/lewtun-drug-reviews/${train_data_path}.jsonl
      --output_path data/preprocessed/procd_${train_data_path}.csv
    deps:
    - data/raw/lewtun-drug-reviews/${train_data_path}.jsonl
    - src/preprocessing.py
    params:
    - train_data_path
    outs:
    - data/preprocessed/procd_${train_data_path}.csv
  feature_engineering_train:
    cmd: python src/feature_engineering.py --procd_data_path data/preprocessed/procd_${train_data_path}.csv
    deps:
    - data/preprocessed/procd_${train_data_path}.csv
    - src/feature_engineering.py
    params:
    - RANDOM_SEED
    - train_data_path
    - procd_text
    - feature_engineering
    outs:
    - data/features/dictionary.pkl
    - data/features/bow_corpus.pkl
    - data/features/tfidf_corpus.pkl
    - data/features/bert_embeddings.pkl
  clustering_bert_train:
    cmd: python src/clustering.py --model_path data/features/bert_embeddings.pkl --log_dir
      clustering_bert
    deps:
    - data/features/bert_embeddings.pkl
    - src/clustering.py
    params:
    - RANDOM_SEED
    - clustering_bert
    outs:
    - ./models/bert_${clustering_bert.algorithm}.pkl
  topic_modeling:
    cmd: python src/topic_modeling.py --procd_data_path data/preprocessed/procd_${train_data_path}.csv
      --dictionary_path data/features/dictionary.pkl
    deps:
    - data/preprocessed/procd_${train_data_path}.csv
    - data/features/dictionary.pkl
    - ./models/bert_${clustering_bert.algorithm}.pkl
    - src/topic_modeling.py
    params:
    - RANDOM_SEED
    - train_data_path
    - procd_text
    - topic_modeling
metrics:
- clustering_bert/metrics.json
- topic_modeling/metrics.json
plots:
- clustering_bert/plots/metrics:
    x: step
- topic_modeling/plots/metrics:
    x: step
