stages:
  extract_sample:
    cmd: python src/extract_sample.py --input_path data/raw/lewtun-drug-reviews/train.jsonl
      --output_path data/raw/lewtun-drug-reviews/sample_train.csv
    deps:
    #- data/raw/lewtun-drug-reviews/train.jsonl
    - src/extract_sample.py
    params:
    - RANDOM_SEED
    - extract_sample
    outs:
    - data/raw/lewtun-drug-reviews/sample_train.csv
  preprocess_train:
    cmd: python src/preprocessing.py --input_path ${train_data_path} --output_path
      data/preprocessed/procd_train.csv
    deps:
    #- ${train_data_path}
    - src/preprocessing.py
    params:
    - train_data_path
    outs:
    - data/preprocessed/procd_train.csv
  feature_engineering_train:
    cmd: python src/feature_engineering.py --input_path data/preprocessed/procd_train.csv
    deps:
    - data/preprocessed/procd_train.csv
    - src/feature_engineering.py
    params:
    - RANDOM_SEED
    - feature_engineering
    outs:
    - data/features/dictionary.pkl
    - data/features/bow_corpus.pkl
    - data/features/tfidf_corpus.pkl
    - data/features/bert_embeddings.pkl
  clustering_bert_train:
    cmd: python src/clustering.py --model_path data/features/bert_embeddings.pkl --log_dir
      clustering_bert
    deps:
    #- data/features/bert_embeddings.pkl
    - src/clustering.py
    params:
    - RANDOM_SEED
    - clustering_bert
  topic_modeling:
    cmd: python src/topic_modeling.py --procd_data_path data/preprocessed/procd_train.csv
      --dictionary_path data/features/dictionary.pkl
    deps:
    - src/topic_modeling.py
    params:
    - RANDOM_SEED
    - topic_modeling
metrics:
- clustering_bert/metrics.json
- topic_modeling/metrics.json
plots:
- clustering_bert/plots/metrics:
    x: step
- topic_modeling/plots/metrics:
    x: step
