stages:
  extract_sample:
    cmd: python src/extract_sample.py --input_path data/raw/lewtun-drug-reviews/train.jsonl
      --output_path data/raw/lewtun-drug-reviews/sample_train.csv --fraction ${extract_sample.fraction}
      --stratify_column ${extract_sample.stratify_column}
    deps:
    - data/raw/lewtun-drug-reviews/train.jsonl
    - src/extract_sample.py
    params:
      #- extract_sample.fraction
      #- extract_sample.stratify_column
    - extract_sample
    outs:
    - data/raw/lewtun-drug-reviews/sample_train.csv
  preprocess:
    cmd: python src/preprocessing.py --input_path data/raw/lewtun-drug-reviews/sample_train.csv
      --output_path data/preprocessed/lewtun-drug-reviews/procd_sample_train.csv
    deps:
    - data/raw/lewtun-drug-reviews/sample_train.csv
    - src/preprocessing.py
    outs:
    - data/preprocessed/lewtun-drug-reviews/procd_sample_train.csv
  feature_engineering:
    cmd: python src/feature_engineering.py --input_path ${feature_engineering.input_path}
      --bow ${feature_engineering.bow} --tfidf ${feature_engineering.tfidf} --word2vec
      ${feature_engineering.word2vec.enabled} --vector_size ${feature_engineering.word2vec.vector_size}
      --window ${feature_engineering.word2vec.window} --min_count ${feature_engineering.word2vec.min_count}
      --epochs ${feature_engineering.word2vec.epochs} --workers ${feature_engineering.word2vec.workers}
      --bert ${feature_engineering.bert}
    deps:
    #- params.yaml
    - src/feature_engineering.py
    params:
    - feature_engineering
    outs:
    - data/features/dictionary.pkl
    - data/features/bow_corpus.pkl
    - data/features/tfidf_corpus.pkl
    - data/features/word2vec_model.pkl
    - data/features/bert_embeddings.pkl
  topic_modeling_bow_tfidf:
    cmd: python src/topic_modeling_bow_tfidf.py --procd_data_path ${topic_modeling_bow_tfidf.procd_data_path}
      --bow_corpus_path data/features/bow_corpus.pkl --tfidf_corpus_path data/features/tfidf_corpus.pkl
      --dictionary_path data/features/dictionary.pkl --lda_n_topics ${topic_modeling_bow_tfidf.lda_n_topics}
      --nmf_n_topics ${topic_modeling_bow_tfidf.nmf_n_topics} --lda_bow_model_path
      data/models/lda_bow_model.pkl --nmf_bow_model_path data/models/nmf_bow_model.pkl
      --lda_tfidf_model_path data/models/lda_tfidf_model.pkl --nmf_tfidf_model_path
      data/models/nmf_tfidf_model.pkl
    deps:
    - data/features/dictionary.pkl
    - data/features/bow_corpus.pkl
    - data/features/tfidf_corpus.pkl
    - data/features/word2vec_model.pkl
    - data/features/bert_embeddings.pkl
    - src/topic_modeling_bow_tfidf.py
    params:
    - topic_modeling_bow_tfidf
    outs:
    - data/models/lda_bow_model.pkl
    - data/models/nmf_bow_model.pkl
    - data/models/lda_tfidf_model.pkl
    - data/models/nmf_tfidf_model.pkl
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
