RANDOM_SEED: 42
train_data_path: sample_train             # one of 'train', 'sample_train'
test_data_path: test
procd_text: lemma_w_stpwrd                # one of 'lemma_wo_stpwrd', 'lemma_w_stpwrd'
extract_sample:
  fraction: 0.2
  stratify_column:
feature_engineering:
  bow: true
  tfidf: true
  ngram: bigram                           # one of 'unigram', 'bigram'
  bert: true
  bert_pretrained_model: bert-base-uncased
clustering_bert:
  algorithm: kmeans                       # one of 'kmeans', 'dbscan', 'hierarchical'
  num_clusters: 2                         # number of clusters for k-means and agglomerative clustering
  eps: 0.2                                # DBSCAN eps
  min_samples: 5                          # DBSCAN min_samples
  #distance_threshold: 0.5                # agglomerative clustering distance threshold
topic_modeling:
  feature: tfidf                          # one of 'bow', 'tfidf'
  algorithm: lda                          # one of 'lda', 'nmf'
  cluster: true                           # 'true' or 'false' indicating if using topic modeling within clusters
  num_topics: 8
