RANDOM_SEED: 42
extract_sample:
  fraction: 0.2
  stratify_column: 'rating'
feature_engineering:
  bow: true
  tfidf: true
  word2vec:
    enabled: true
    vector_size: 100
    window: 5
    min_count: 1
    epochs: 10
    sg: 0
  bert: true
topic_modeling_bow_tfidf:
  lda_n_topics: 10
  nmf_n_topics: 10