RANDOM_SEED: 42
extract_sample:
  fraction: 0.2
  stratify_column: 'rating'
feature_engineering:
  bow: true
  tfidf: true
  word2vec:
    enabled: true
    vector_size: 100
    window: 5
    min_count: 1
    epochs: 10
    sg: 0
  bert: true
topic_modeling:
  num_topics: 10
clustering:
  num_clusters: 10  # number of clusters for k-means and agglomerative clustering
  eps: 0.2  # DBSCAN eps
  min_samples: 5  # DBSCAN min_samples
  #distance_threshold: 0.5  # agglomerative clustering distance threshold
